apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hoyolab-check-in.fullname" . }}
type: Opaque
data:
  LTOKEN_V2: "{{ .Values.config.hoyolab_credential.ltoken_v2 | b64enc }}"
  LTUID_V2: "{{ .Values.config.hoyolab_credential.ltuid_v2 | b64enc }}"
  DISCORD_WEBHOOK: "{{ .Values.config.discord_webhook.webhook | b64enc }}"